In [30]:
import pandas as pd

In [31]:
df = pd.read_csv("diabetes.csv")
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [32]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [33]:
df.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [34]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [35]:
# Checking the DataFrame having any Null values
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [36]:
df.shape

(768, 9)

In [37]:
# Define the Target  variable
y= df[['Outcome']]
y

     Outcome
0          1
1          0
2          1
3          0
4          1
..       ...
763        0
764        0
765        0
766        1
767        0

[768 rows x 1 columns]

In [38]:
x = df.iloc[:,:8]
x

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [39]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [40]:
print("x_train: ",x_train.shape)
print("y_train: ",y_train.shape)
print("x_test: ",x_test.shape)
print("y_test: ",x_test.shape)

x_train:  (614, 8)
y_train:  (614, 1)
x_test:  (154, 8)
y_test:  (154, 8)

In [41]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [42]:
lr.fit(x_train,y_train)

LinearRegression()

In [43]:
m = lr.coef_
print("Coeff: ",m)

Coeff:  [[ 0.02604481  0.00636631 -0.00238738  0.00072783 -0.00022277  0.01275374
   0.16008617  0.00127011]]

In [44]:
c = lr.intercept_
print("intercept: ",c)

intercept:  [-0.87023669]

In [45]:
y_predict = lr.predict(x_test)
y_predict

array([[ 1.90462826e-03],
       [ 2.39429343e-01],
       [ 1.10562272e-01],
       [ 3.11236987e-01],
       [ 5.70174319e-01],
       [ 1.50343359e-01],
       [ 5.37976118e-02],
       [ 4.58059182e-01],
       [ 4.81570449e-04],
       [ 5.49684168e-01],
       [ 4.03355822e-01],
       [ 4.30315206e-01],
       [ 6.58903961e-01],
       [ 2.42115626e-01],
       [-1.49374524e-01],
       [ 7.53330954e-01],
       [ 8.07481119e-01],
       [-6.07681249e-02],
       [ 3.16057021e-01],
       [ 8.52796982e-01],
       [ 9.83320931e-01],
       [ 7.56821710e-01],
       [ 1.60464626e-01],
       [ 4.31005605e-01],
       [ 1.13813261e-01],
       [ 4.87510105e-02],
       [ 5.78379810e-01],
       [ 4.25668664e-01],
       [ 2.39461800e-01],
       [ 3.34672688e-01],
       [ 3.14173416e-01],
       [ 4.42232972e-01],
       [-2.26999855e-01],
       [ 2.91254808e-01],
       [ 4.01255479e-01],
       [ 1.03437687e+00],
       [ 3.72530667e-01],
       [ 7.22801124e-01],
       [ 3.49484092e-01],
       [ 2.25941837e-02],
       [ 2.43506139e-01],
       [ 8.88253011e-02],
       [ 4.49445701e-01],
       [ 2.45962179e-01],
       [-7.70729226e-02],
       [-2.10660582e-02],
       [ 3.06661242e-01],
       [ 4.43499558e-01],
       [ 1.24883978e-01],
       [ 4.24915795e-01],
       [ 1.30895173e+00],
       [ 1.50886052e-01],
       [ 4.16533644e-01],
       [ 6.94258229e-01],
       [ 4.04976947e-01],
       [ 4.67764385e-01],
       [ 9.76882119e-01],
       [ 4.41491533e-01],
       [ 4.04585332e-01],
       [-8.07574495e-03],
       [ 4.06779233e-01],
       [ 8.38571888e-01],
       [ 8.06922455e-01],
       [ 8.46318647e-01],
       [ 3.69137655e-01],
       [ 1.20133217e-01],
       [ 9.93040684e-01],
       [ 2.76544686e-01],
       [ 3.27572889e-01],
       [ 3.82231713e-01],
       [ 1.33369898e-01],
       [ 8.35535945e-02],
       [ 4.70588650e-01],
       [ 1.14728281e-01],
       [ 1.07312682e-01],
       [ 5.03158983e-01],
       [ 3.98155885e-01],
       [ 8.33613357e-02],
       [ 2.90843027e-01],
       [ 3.01041410e-01],
       [ 9.84296581e-04],
       [ 2.79624690e-01],
       [ 4.20914584e-02],
       [ 2.88015704e-01],
       [ 6.27604697e-01],
       [ 3.53374641e-01],
       [ 1.25388318e-01],
       [ 1.40678069e-01],
       [ 2.58727037e-01],
       [ 5.58078637e-01],
       [ 1.61267803e-01],
       [ 3.20402737e-01],
       [ 2.56852097e-01],
       [-4.70231666e-03],
       [ 2.31066166e-01],
       [ 6.48184143e-01],
       [ 3.62164715e-01],
       [ 5.41454475e-01],
       [ 6.37916720e-01],
       [-8.31903877e-03],
       [ 4.64526854e-01],
       [ 5.47705232e-01],
       [ 1.43616765e-01],
       [ 9.59343197e-02],
       [ 2.35705354e-01],
       [ 1.28879153e-01],
       [ 1.08606330e+00],
       [ 1.99088547e-01],
       [ 1.40016474e-01],
       [-5.83608634e-01],
       [-2.73060347e-02],
       [ 3.28375418e-01],
       [ 4.36660388e-01],
       [ 5.54287654e-02],
       [ 3.25147232e-01],
       [ 6.93670686e-01],
       [ 4.26945939e-01],
       [ 3.04944504e-01],
       [ 1.85211526e-01],
       [ 1.67746314e-01],
       [-1.80615760e-01],
       [ 3.26557808e-01],
       [ 1.39381357e-01],
       [ 1.78091737e-01],
       [ 3.41070182e-01],
       [ 8.18586853e-01],
       [ 1.69655823e-01],
       [ 4.79624270e-01],
       [ 4.17760972e-01],
       [ 4.52893101e-01],
       [ 5.91404485e-01],
       [ 3.17548499e-01],
       [ 4.47173930e-01],
       [ 7.40705662e-03],
       [ 6.01495923e-01],
       [ 6.12203355e-01],
       [ 3.58707636e-01],
       [ 3.95741415e-01],
       [ 2.36207678e-01],
       [ 5.30468329e-01],
       [ 2.02464254e-01],
       [ 6.23832275e-01],
       [ 2.09856894e-01],
       [ 3.57862524e-01],
       [ 2.72911594e-01],
       [ 2.61865839e-01],
       [-4.30886249e-02],
       [ 5.15417976e-01],
       [-5.26963712e-02],
       [ 1.71880244e-01],
       [ 7.64668254e-02],
       [ 2.86708156e-01],
       [ 5.80051113e-01],
       [-1.31832150e-01]])

In [46]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [47]:
print("MSE: ",mean_squared_error(y_test,y_predict))
print("MEA: ",mean_absolute_error(y_test,y_predict))
print("R2 Score: ",r2_score(y_test,y_predict))

MSE:  0.167279325356488
MEA:  0.3347207586149436
R2 Score:  0.1911933781540327

In [50]:
predict = lr.predict([[1,85,66,29,0,26.6,0.351,31]])
predict

C:\Users\ADMIN\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[-0.00470232]])